# Generated by Django 3.1.5 on 2021-01-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='Timer',
        ),
    ]
